### ISSUE TITLE
ansibleのトラブル対応１

### ISSUE THREAD

**Issue by remotelocal** [remotelocal/web#1]
http://qiita.com/ea54595/items/12ab7b3a8213b35cca10

production.rbのユーザがvagrantになっているので、書き換える
```
---
- hosts: app
  sudo: true
  vars:
    hostname: server-production
    environtment: production
    ruby_version: 2.1.2
    rbenv_root: /home/vagrant/.rbenv
    rbenv_bin: /home/vagrant/.rbenv/libexec/rbenv
  roles:
    - common
    - rvm
    - nginx
    - mysql
    - rails
```
